### ISSUE TITLE
Allow registering blueprints before app initialisation

### ISSUE THREAD

**Issue by jrast** [marshmallow-code/flask-smorest#175]
Currently it is not possible to register blueprints on the api before the api was initialized with an app (`init_app` called) because `Api.register_blueprint` assumes that `_app` is already set. It would be nice if the blueprints can be registered prior to app initialisation. I created a custom subclass of the Api wich allows early registration of blueprints:

````python
class CustomApi(Api):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._run_on_init = []

    def register_blueprint(self, bp, **options):
        self._run_on_init.append(lambda: Api.register_blueprint(self, bp, **options))

    def init_app(self, app, *, spec_kwargs=None):
        super().init_app(app, spec_kwargs=spec_kwargs)
        for method in self._run_on_init:
            method()
````

This is just an idea, maybe there are downsides to this. I liked the idea to register all the blueprints in the `__init__.py` of my API where also the Api extension is created. In my `create_app` function i just need to call `api.init_app(app)` and the blueprints are registered automatically.

**Comment by lafrech** [comment]
Not a strong objection but I don't really see a huge benefit to this. In any case you need to import the blueprints in the `Api`  init file.

I wouldn't use a `_run_on_init` mechanism if it was just for this. I'd change register blueprint to be lazy, I suppose. Like I did already with `register_converter`. We could do it relatively easily but the gain doesn't seem worth the effort.

A `run_on_init` feature like the one you expose here goes beyond this issue's scope and could be useful for other needs. It might be a useful feature to add. Likewise, not a strong objection, but if there's not much demand I won't do it.

Besides, your sample code shows it's easy enough to achieve in user land, so I don't have a strong incentive to implement it in the core.

I'm going to close this for now because the (small) added value doesn't seem worth the (small) added API surface.

Anyone willing to allow blueprint registering before app init, please feel free to comment here and we can reconsider. `register_converter` / `register_field` should be checked for inspiration.

Anyone willing to add a generic init callback registering mechanism, please open a dedicated issue.
