### ISSUE TITLE
Question: Compatibility with other non-smorest blueprints?

### ISSUE THREAD

**Issue by dsposito** [marshmallow-code/flask-smorest#187]
I have a Flask app with multiple blueprints (API, web frontend, docs, etc). I'd like to use Smorest only for my API blueprint.

I've updated my API blueprint to use Smorest's Blueprint class - the @arguments and @response are working great. However, it's not handling validation errors from Marshmallow properly when those http exceptions are raised (e.g., if a POST request body is missing a required field). The error response body is HTML instead of JSON and is missing error details.

Example error response:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>422 Unprocessable Entity</title>
<h1>Unprocessable Entity</h1>
<p>The request was well-formed but was unable to be followed due to semantic errors.</p>
```

I've omitted using Smorest's [Api](https://flask-smorest.readthedocs.io/en/latest/api_reference.html#flask_smorest.Api) class because I don't want to replace my entire `app` with Smorest's Api wrapper since not all of my app's blueprints are actually API-related.

Any suggestions on how to get the error handling response formatted properly and how to proceed in general?

Thanks!

**Comment by dsposito** [comment]
I ended up getting this to work by using register_error_handler() on my Smorest API blueprint and then copying the logic from Smorest's ErrorHandlerMixin method: https://github.com/marshmallow-code/flask-smorest/blob/master/flask_smorest/error_handler.py#L32

It's working well so far at the blueprint level. Happy to hear about any other suggested approaches!

**Comment by lafrech** [comment]
I'm glad this works for you. However, working without the `Api` class is not a setup we support and I can't provide a recommended way to achieve this.

**Comment by ddorian** [comment]
@lafrech 

What if, instead of doing this line: https://github.com/marshmallow-code/flask-smorest/blob/e04d3a7b5976a1cbb50aad5db5e71932e178a514/flask_smorest/error_handler.py#L30

We just register the error handler on each blueprint:
```python
for blueprint in self._app.extensions["flask-smorest"]["blp_name_to_api"].values():
     blueprint.register_error_handler(HTTPException, self.handle_http_exception)
````

**Edit: the code above doesn't work, because it references the `Api` class, but you get the point that registering the handler in each blueprint. Can even be done inside `register_blueprint()` as an example.**

**Edit2**: The error handler needs to be added before the blueprint has been registered.

As an alternative, I currently register an error handler on the other blueprints that don't serve json. The blueprint error handler overrides the app error handler.
