### ISSUE TITLE
Adding examples to endpoints

### ISSUE THREAD

**Issue by fbergroth** [marshmallow-code/flask-smorest#19]
I'm looking for a way to add [examples](https://swagger.io/docs/specification/adding-examples/).

I'm trying to add them with `Blueprint.doc`, but it seems they are thrown away by `Blueprint._prepare_doc`.

Is there some other way?

**Comment by lafrech** [comment]
The only thing I've ever been doing to provide examples is passing an `example` kwarg to schema fields.

```py
class UserSchema:

    name = fields.String(required=True, example='John Doe')
```

I can't promise I'll be looking into it soon, but can you provide more information to help reproduce?

- OpenAPI version
- Example (what you pass into `@doc` decorator)

If we can't provide a convenient way of adding examples, we should at least ensure we don't drop what the user passes manually in `@doc`.

**Comment by fbergroth** [comment]
Hi, sorry, I forgot about this issue and solved it another way.
> OpenAPI version

I'm using `OPENAPI_VERSION = '3.0.1'`

> Example (what you pass into `@doc` decorator)

I was trying to add these examples to the output, but couldn't find a way.
```
{'requestBody': {'content' : {'application/json' : {'example': {'test': 123}}}}}
{'responses': {200 : {'application/json' : {'example': {'test': 123}}}}}
```
In the end, i hooked into the `APISpec` instance and modified the `_paths` data after registerering the blueprints.

**Comment by lafrech** [comment]
I think I see the root cause for this.

The doc structure differs between OpenAPI v2 and v3. However, at `Blueprint` creation time, the OpenAPI version is unknown. It is known at app init.

Therefore, when applying `Blueprint` decorators, we only store a temporary doc structure. Then when registering the view in docs, we map this information to the final version dependent structure.

In practice, for historical reasons and because OpenAPI 2 is a bit simpler, the temporary structure is the OpenAPI v2 structure and changes are only needed for OpenAPI v3. Those changes are applied in `_prepare_doc`. Things may change in the future, the temporary structure may also differ from OpenAPI v2. This is internal details. The good thing about this is that flask-rest-api abstracts some version related details (the `{'content' : {'application/json': ...}}` nesting of  the response).

I think the information you're adding using `@doc` is lost in `_prepare_doc`. We need to fix `_prepare_doc` to avoid this.

There are two ways of dealing with this.

- Either pass `@doc` content as is into the docs.

- Or decide that we want to provide a nice abstraction layer and also modify what is passed into `@doc` to adapt it to the OpenAPI version.

While the latter sounds appealing, it could be a trap. The abstraction layer I'm talking about is not well defined. As I said, it is internals. And I think the user expects information in `@docs` to be copied verbatim.

So I'm leaning towards not trying to play too smart and go with the former.

This will make things a little more verbose for the user (need to write `application/json`, etc.) but it should be more reliable.

That's what `@doc` has always been: a way to pass explicitly the information that could not be inferred by flask-rest-api. It is a last resort thing.

I don't think many users maintain an app using both OpenAPI versions, so hardcoding version related stuff in `@doc` isn't a blocker.

If we want to provide an abstraction to provide examples, then maybe we should add an `@examples` decorator.

The cleanest way to implement what I'm saying above could be to postpone the deep update of `@doc` content to registration time, after `_prepare_doc` is applied. This means carrying both auto doc and manual doc all along until registration. This will make the code even more complex than it already is, but that's life.

**Comment by lafrech** [comment]
I tried to implement logic described in above comment:

https://github.com/Nobatek/flask-rest-api/tree/dev_19_merge_manual_doc_after_prepare_doc

Feedback welcome.

**Comment by fbergroth** [comment]
Looks good. I haven't tested it yet though, but it seems like the correct way to do it.

Perhaps you want to allow multiple `@doc` decorations (by merging `_api_manual_doc`) which I think worked before.

**Comment by lafrech** [comment]
Yep. Nice catch. Thanks.

I'd rather maintain a "view func <-> doc" mapping in the spec object than add arbitrary private attributes (`_apidoc` and `_api_manual_doc`)  to the view func objects, but the mapping approach can't work due to the decorators returning different objects. At least I didn't find how to get it to work.

**Comment by fbergroth** [comment]
Yeah, I see the issue. I think you must add the `_api_manual_doc` to all the decorators as well?
```
def decorator(func):
    func._api_manual_doc = getattr(func, '_api_manual_doc', {})
```
You could use a custom `functools.wraps` for the decorators that copies/propagates all of the private attributes. Not that nice, but I don't see a better way either.

**Comment by lafrech** [comment]
No, I think they do propagate already.

I just meant adding private attributes to external objects is a smell.

Generally, I'd rather have

```py
    my_mapping[func_obj] = doc_dict
```

than

```py
    func_obj._apispec = doc_dict
```

so as not to modify the view function object.

But the key (the view func) registered by a decorator would be wrong when the next decorator returns another view func.

By the time you want to get the doc dict, all you have is the decorated func object and the key in the mapping may be the func object before another decoration, so the link is lost.

No big deal. Let's keep view func object attributes for now.

**Comment by lafrech** [comment]
I just updated the dev branch: https://github.com/Nobatek/flask-rest-api/tree/dev_19_merge_manual_doc_after_prepare_doc to fix the case where doc is called twice, and to add tests.

Also, I just realized that status codes are registered as integers in the spec while I think they should be strings. I didn't find any explicit requirement for strings but all examples use strings. All I found was this PR: https://github.com/OAI/OpenAPI-Specification/pull/500. I think I'll change to strings. It will break your code as you're using integers.

**Comment by fbergroth** [comment]
Ah, good to know. Is there anything else you plan to add before merging it?

**Comment by lafrech** [comment]
I'll make the int -> string change independently. I'd rather be sure about what the doc requires before doing it.

Regarding this change, I think it is complete. I just need to take the time to clean it up, maybe find a better attribute name. Then update changelog, release, etc.

**Comment by lafrech** [comment]
This is fixed in master.

Would you like to test before I release?

**Comment by fbergroth** [comment]
Nice! Looks ready to me.

**Comment by lafrech** [comment]
0.15.0 allows the user to provide examples in the `response` and `arguments` decorators.

It comes with a breaking change that may impact people passing response examples using the `doc` decorator. See https://github.com/Nobatek/flask-rest-api/issues/60#issuecomment-487856593.
