### ISSUE TITLE
Support webargs fields or Marshmallow instance with options in arguments

### ISSUE THREAD

**Issue by ruathudo** [marshmallow-code/flask-smorest#2]
Hi,
I feel it would be handy if we can use webargs dict with arguments decorator.
Or if we can use Marshmallow instance with some params for example:

`@blp.arguments(Schema(only=["first", "second"]))`

The reason is, we just need one Schema model for all arguments request. We can decide which params needed to be there, don't need all. 

I know we can have load_only or dump_only in Marshmallow. But it would be more flexible if we can use instance with only=, partial=, exclude=...

I really like this library. Found it is the best fit for my projects.
If you are planing to support this in long run, I would like to help.
Thanks

**Comment by lafrech** [comment]
Thanks for the positive feedback.

I never tried to pass `dict`s because I always use schemas. I have no objection to that if it adds flexibility. From a quick glance, I don't see anything blocking this.

Likewise, marshmallow `Schema` instances with parameters should be accepted as well.

In both case, I think it should work already, at least from webargs point of view. However, there may be issues with the documentation. Issues that may lie in apispec rather than flask-rest-api.

If you want to help on this, please be more specific about what you tried, what happened, what you expected,...

One nice feature of flask-rest-api/apispec is the ability to declare schemas (using `definition`) tu re-use them throughout the spec. The matching is done on the schema class, so if you're passing a `Schema` with different parameters to several view functions, and if the schema class is added as a definition, all views will have the schema replaced with a reference to the same class definition, which is wrong. In other words, customizing schemas on-the-fly breaks the definition mechanism. I think this is one of the reason we stayed away from that use case. But if you don't mind losing the definition feature, then I don't see any other blocking issue.

**Comment by lafrech** [comment]
Regarding marshmallow schemas with arguments, this is an apispec issue discussed here: https://github.com/marshmallow-code/apispec/issues/169.

Regarding the use of `dict`s, I'm open. @ruathudo, are you still interested in investigating this?

**Comment by lafrech** [comment]
IIUC, the marshmallow schema modifiers case is solved in apispec 1.0.0.

If anyone wants to investigate the `dict` (rather than `Schema`) argument case, please open a new issue.
