### ISSUE TITLE
Webargs 7.0 breaks usage of unknown = EXCLUDE

### ISSUE THREAD

**Issue by shughes-uk** [marshmallow-code/flask-smorest#200]
Per the [webargs changelog](https://github.com/marshmallow-code/webargs/blob/dev/CHANGELOG.rst)

`Parser.use_args` , now requires you to set `unknown=None` be passed or `Parser.DEFAULT_UNKNOWN_BY_LOCATION` set if you your schema model parameter is to be respected it seems.

The result of this is that all our Schemas are defaulting to `unknown=raise` which broke things. Workaround for this is to set a requirement of `webargs<7.0.0`

**Comment by lafrech** [comment]
Indeed, behaviour regarding unknown parameters has changed in webargs 6 and 7.

webargs 7 provides more flexibility and sensible defaults.

See https://webargs.readthedocs.io/en/latest/upgrading.html and https://webargs.readthedocs.io/en/latest/advanced.html#advanced-setting-unknown.

------------------------------------------------------

Dependencies may introduce breaking changes in major versions.

I've been wondering. We could pin webargs or apispec to current stable version, but then bumping to next major would require a new, perhaps breaking, major flask-smorest version. I don't think this is desirable. There are frequent major version in those libs but for most of them the breaking change is marginal. This is independent of flask-smorest.

Overall, I don't think flask-smorest should do anything about it, but I'm open to discussion about it.

Regarding the specific change above, the user should be responsible for checking webargs changelog when upgrading to a now major.

**Comment by shughes-uk** [comment]
I don't think its fair to require the user to read and understand change logs for dependencies of dependencies. We don't directly depend on webargs, but the latest version was just installed as part of a fresh build of our product, and broke it. 

To prevent that from happening I would have had to be intimately familiar with the inner workings of flask-smorest, and have read every single change log from every updated package, and also be using something like pyenv or poetry which generates lockfiles (we just use a requirements.txt at the moment). Even then if you use those environment managers, adding flask-smorest today would result webargs 7 being installed so you're starting out in a broken state.

I think you can get away without preventing major version updates in your dependencies, but when a bug like this occurs you should either resolve it or add a temporary version restriction to stop major issues cropping up.

**Comment by bryevdv** [comment]
@lafrech as one library maintainer to another, it is 100% a library maintainers responsibility to ensure that "pip install foo" or "conda install foo" installs with correct versions of *its own* depedencies. If one of your dependencies introduces a breaking change *for the library* then the correct course of action is to quickly issue a new point release that pins or limits the dependency version from above to insulate users from this breakage. Then when you want to update the library to use the new version of the dependency, switch limiting the dependency version from below.

**Comment by lafrech** [comment]
I think I conform to that plan. I don't pin dependencies, but when a new major dep version is released that breaks flask-smorest compatibility, I either issue a new flask-smorest version right away or issue a quickfix release in which I pin the dep version until a new releases fixes compatibility.

I generally do this quick as I'm aware of apispec and webargs releases since I also co-maintain them. I should configure dependabot some day.

I've always been wondering if I should lock dependencies versions earlier, I mean preventively before a breaking release is out, but I think this is common practice. AFAIK, that's what Flask do: https://github.com/pallets/flask/blob/master/setup.py.

The case in OP is a bit specific. flask-smorest itself is not broken by the release. All tests pass. If I were to issue a webargs 7 compatible version, it would be just the same. I could release a new version pinning webargs < 7, then issue a major flask-smorest with the exact same code and webargs 7 documenting a breaking change about webargs being modified. But that sounds kinda weird.

flask-smorest uses apispec and webargs internally but it doesn't wrap them completely. Some features, like registering components (apispec) are directly provided by those libs and a change in there would break user code without breaking flask-smorest compatibility and unit tests. I'm not sure I need to manage this with flask-smorest releases.

Flask is compatible with both pre and post 1.0 werkzeug versions despite the potential breaking changes in them. Perhaps the difference is that those breaking changes would only affect users explicitly importing werkzeug, but I'm not sure about that.

I totally realize the inconvenience, but I'm not sure how to address that reasonably and efficiently.

In any case, the plan described above doesn't prevent a user from using a version from flask-smorest with a recent dep version that wouldn't be compatible, either because that flask-smorest version is outdated or because the new dep release was just released. So ultimately, a production deployment should be covered by unit tests and pinned dependencies (e.g. requirements.txt).

**Comment by lafrech** [comment]
I did run the unit tests immediately after the webargs release and no test was broken. dependabot wouldn't have alerted about the change.

This is because the modified feature is just republished by flask-smorest in the use_args decorator but not tested in the test suite, as I try not to test the deps but only flask-smorest features.

I guess what you're asking for is for flask-smorest to totally wrap (and test, which means provide by API contract) features from apispec and webargs. I'm not sure this is a reasonable thing to do. But I'm still open to discussion about this.

**Comment by bryevdv** [comment]
You shouldn't test your dependencies, but you should maintain that default values and behaviors remain stable across releases under test, in general. If your behavior is implicitly coupled to some default in the dependency, then that specifically does need to be covered in one way or another.

**Comment by shughes-uk** [comment]
Is there any kind of workaround for this beyond locking a dependency? Having the `unknown` value I set in the `Meta` class on my schema's be ignored in favor of `raise` is quite breaking.

**Comment by lafrech** [comment]
Quick (and dirty ?): monkeypatch.

```py
from webargs.flaskparser import FlaskParser

# Set to None to avoid forcing RAISE over EXCLUDE from base schema
FlaskParser.DEFAULT_UNKNOWN_BY_LOCATION["json"] = None
```

Perhaps cleaner to subclass parser then subclass Blueprint to set new parser.

```py
from webargs.flaskparser import FlaskParser as FlaskParserOrig
from flask_smorest import Blueprint as BlueprintOrig


class FlaskParser(FlaskParserOrig):
    DEFAULT_UNKNOWN_BY_LOCATION = ... the behaviour you want


class Blueprint(BlueprintOrig):
    ARGUMENTS_PARSER = FlaskParser()
```

See https://webargs.readthedocs.io/en/latest/advanced.html#advanced-setting-unknown for explanations and values to put in there.

**Comment by sirosen** [comment]
I think it would be good for `flask-smorest` to put upper bounds on the versions of its dependencies. It's more important if 1.0 is released and the classifier is switched from "Beta" to "Production" -- then a stronger guarantee of compatibility will be offered.

There's not much harm in releasing new major versions of `flask-smorest` every time a major version of one of its dependencies ships. It's slightly more work for us (yes, "us": I'm willing to help out 😉 ), but IMO it's worth it.

But even without going to 1.0, I think it's a better experience for users if `pip install 'flask-smorest==x.y.z'` always grabs the same major versions of the dependencies.

> There are frequent major version in those libs but for most of them the breaking change is marginal.

FWIW, I don't want to do another major version of `webargs` for a long while. I considered 7.0 necessary because of the usages like dict-schemas on `location="headers"`. I'll advocate for working up 8.0.0 if we find that 7.x is really problematic for some users and we can't come up with a backwards-compatible way of handling it, but it may be worth noting that I'd like to slow down the pace of major releases a bit.

> I don't think its fair to require the user to read and understand change logs for dependencies of dependencies.

I agree with this. The docs and readme don't give users reason to expect that second-order dependencies could change in breaking ways, and change the behavior of this library.

If we're looking at `flask` for an example, I think it's also worth noting that their 0.12.x line has to pin `werkzeug`:
https://github.com/pallets/flask/blob/79c71f24e4cb064852e2cbbfef78a0a051eb7ced/setup.py#L74

By leaving their versions open, I think the pallets team is making it possible to release a `werkzeug 2.0` which is compatible with `flask 1.x` but makes other breaking changes. I'm not sure that I want to follow their lead on this though. They're committed much more strongly to not making backwards-incompatible changes: even `marshmallow` moves much faster than `flask`.

If we want to avoid restricting dependency versions (per above I think upper bounds would be good, but I'm also not a maintainer of this lib), I think the docs need to call that out. If the docs say "you need to pin your webargs version", then the situation becomes very different.

> Even then if you use those environment managers [poetry, pip-tools, etc], adding flask-smorest today would result webargs 7 being installed so you're starting out in a broken state.

This is not a fair assessment. The lockfile systems guarantee that "what worked today works tomorrow". `flask-smorest` is compatible with `webargs>=7,<8`, so the tools should allow it.
The point in time at which you introduce these things into a workflow matters -- `poetry` and its ilk only protect you from second- and third-order dependencies changing if you introduce them at time when your application works with the specified package versions.

> when a bug like this occurs

I don't believe that there is a bug. The change in behavior in webargs -- which does not respect `Meta.unknown` unless explicitly instructed to do so -- is intentional and, from what @lafrech has said, `flask-smorest` works fine with this version of `webargs`.

Aside: although unstated, I'm well aware that the change in `webargs` requires annoying fiddling for the OP and similar usages. My own use of the library is the same. But the `unknown` behaviors were the best we could work out to handle _other_ use-cases gracefully.

> Is there any kind of workaround for this beyond locking a dependency?

Today, right now, this minute? No. I would recommend you add `webargs<7`, `apispec<5`, and `marshmallow<4` to any requirements where you only have `flask-smorest` today.
If we change how things are done in `flask-smorest`, possibly something different will become possible.

> If I were to issue a webargs 7 compatible version, it would be just the same. I could release a new version pinning webargs < 7, then issue a major flask-smorest with the exact same code and webargs 7 documenting a breaking change about webargs being modified. But that sounds kinda weird.

Agreed, with the state we're in right now, it seems pretty weird. But it's also pretty easy.

I think I'd do this if it were up to me in versions 0.26.0 and 0.27.0 .
That solves things for the OP (just use `==0.26.0`) and gets things running smoothly again.

**Comment by lafrech** [comment]
Here's another example.

`requests` are bounding their dep versions to avoid getting caught by a breaking change on its release.

https://github.com/psf/requests/blob/c2b307dbefe21177af03f9feb37181a89a799fcc/setup.py#L44-L48

But once the new dep major version is out, they add support for the new version in a bugfix release:

https://github.com/psf/requests/blob/master/HISTORY.md#2251-2020-12-16
https://github.com/psf/requests/commit/516f84f490ccd352672847c6a3d23c67a13b3f98

I suppose they assume chardet is an internal detail and/or for any reason, moving to v4 isn't likely to cause issues in user code. This is totally possible if the lib features are not exposed to the user. (A user calling chardet in his own code would of course be responsible for pinning it.)

The difference here is that flask-smorest does not hide apispec/webargs to the user so bumping them can be seen as a breaking change.

Alright, I guess I'll be bounding dep versions and issuing major versions when bumping dep versions if appropriate.

I'm not sure it would be needed for marshmallow because the user must be importing marshmallow somewhere to build his schemas so it is not an implementation detail anymore and he's responsible for pinning it. Likewise with Flask. And werkzeug compatibility should be handled by flask. Overall, only webargs and apispec versions bump should require a major flask-smorest release.

Yet, I don't intend to duplicate tests and code, so apispec and webargs should only be tested in their own test suite (unless I want to test a feature here to check its integration) and I may refer to their doc from flask-smorest doc.

**Comment by lafrech** [comment]
I just released 0.25.1 and 0.26.0 to address this.

Thanks @shughes-uk and @bryevdv for expressing your concerns.

Thanks @sirosen for sharing your wisdom.

**Comment by AbdealiLoKo** [comment]
Got the same issue :) And was reading the flask-smorest ChangeLog (thanks to dependabot)
I found: https://github.com/marshmallow-code/flask-smorest/blob/0.26.0/CHANGELOG.rst#0260-2020-12-17
saying:
 > Backwards-incompatible: Support webargs 6. Drop support for webargs 7

Was that meant to be the opposite ? I.e. Support webargs 7 and drop webargs 6 support ?

**Comment by lafrech** [comment]
Oops. Fixed. Thanks for reporting.
