### ISSUE TITLE
New warning 'item_count not set in endpoint' with 0.26.0

### ISSUE THREAD

**Issue by bkircher** [marshmallow-code/flask-smorest#204]
Hey there, 

This warning is now triggered with 0.26.0 release:

```
pagination.py:202: UserWarning: item_count not set in endpoint …
```

Didn't happen with 0.25.1 or 0.24.1

A pytest test case (roughly) that triggers that warning:

```
@bp.route("/test", methods=["GET"])
class Test(MethodView):
    @api.paginate()
    def get(self, pagination_parameters: PaginationParameters):
        pagination_parameters = PaginationParameters(1, 10)
        pagination_parameters.item_count = 0
        return {}


def test_something(client):
    resp = client.get("/api/v1/test")
    assert resp.status_code == 200
```

Am I holding it wrong?

**Comment by lafrech** [comment]
This warning is meant to tell the user he didn't set the item count.

It used to be looged in application log but I changed this in 0.26.0 because it should be a warning. The fact that you never saw it before confirms that a warning is better than forcing this into the app logs.

However, your example shows that you did set the item count, so there must be something wrong somewhere. I just cheked the condition and I do check `item_count is None` and not just falsy (`not item_count`). Further investigation needed.

**Comment by lafrech** [comment]
Oh, I get it. You shouldn't instantiate a `PaginationParameters` in the view function. It doesn't even get out of the function.

You must use the instance passed as argument.

```py
@bp.route("/test", methods=["GET"])
class Test(MethodView):
    @api.paginate()
    def get(self, pagination_parameters: PaginationParameters):
        # Remove this line
        # pagination_parameters = PaginationParameters(1, 10)
        pagination_parameters.item_count = 0
        return {}
```
