### ISSUE TITLE
Bug: Webargs 7 excludes unknown query args by default instead of raise exception

### ISSUE THREAD

**Issue by dsposito** [marshmallow-code/flask-smorest#211]
**Context**
One of my flask smorest API endpoints optionally allows a `first_name` query param to be provided to filter the list of returned users:
```
@api.arguments(RetrieveUserQueryArgsSchema, location="query")

...

class RetrieveUserQueryArgsSchema(Schema):
    """
    Defines the allowed query parameters for retrieving users.
    """

    first_name = fields.String()
```

_If an unknown param (e.g., "last_name") is provided, an exception is normally raised._

**Problem**
However, after upgrading my `webargs` pip dependency to [version 7](https://webargs.readthedocs.io/en/latest/changelog.html), I noticed by default it **excludes** unknown query params rather than raise an exception. **This is breaking my automated tests.**

**Solution?**
After ensuring I have the latest version of flask, marshmallow, smorest and webargs, neither of these solutions work:
- explicitly setting `unknown = RAISE` as mentioned [here](https://flask-smorest.readthedocs.io/en/latest/arguments.html#multiple-arguments-schemas)
- adding `DEFAULT_UNKNOWN_BY_LOCATION = {"query": ma.RAISE}` to `RetrieveUserQueryArgsSchema` as mentioned [here](https://webargs.readthedocs.io/en/latest/changelog.html#b1-2020-09-11)

What's the correct fix for this? Perhaps my syntax isn't quite right or is this a flask-smorest bug given that webargs 7 was released very recently (mid December)? Thanks!

**Comment by shughes-uk** [comment]
A solution to this might be to allow something like. 
```python
from flask_smorest import api

api = Api(flask_parser_kwargs={"DEFAULT_UNKNOWN_BY_LOCATION": {"query": ma.RAISE}})
```

At the moment the webargs FlaskParser is created by `ArgumentsMixin` with no parameters.

Another note is that the `Multiple Arguments Schemas` section of the documentation is incorrect. Meta.unknown is currently overridden by webargs. So for your first workaround to work you'd have to do 

`@api.arguments(RetrieveUserQueryArgsSchema, location="query", unknown=none)`

Then it will respect the `Schema.Meta.unknown` value

**Comment by lafrech** [comment]
There was a huge rework in webargs 6 that made the parsers load all the data from a location using a given schema rather than picking data for each declared field. This was a great change for many reasons, including the possibility to use post_load decorated methods and all sorts of schema features. The downside of this is that webargs would then raise by default on unknown keys, which is fine for JSON body inputs but generally wrong for query args (I'd consider the OP's case an exception) or headers, for instance. Users had to explicitly set unknown to exclude where needed, which was a pain. Webargs 7 addressed this by setting different default behaviours for each location, basically raise for body locations and exclude for the others. Those default values can be overridden, of course. I admit this is hidden in flask-smorest and poorly documented (worse, the doc still includes a wrong example I need to fix). Those default values should be slightly modified in webargs 8. See https://github.com/marshmallow-code/webargs/issues/580 for more.

The unknown value set in the parser for each location (if not None) overrides the value from the schema.

I think the whole feature can be disabled by setting `DEFAULT_UNKNOWN_BY_LOCATION` to `None`, which brings us back to webargs 6 behaviour. But I wouldn't advise this. Webargs 7 behaviour is nice and can be tweaked if needed. In the case described in OP, we want to raise on query args, therefore we need to set `query` to `RAISE` as said above.

This can be done by mutating the parser class:

```py
from webargs.flaskparser import FlaskParser
FlaskParser.DEFAULT_UNKNOWN_BY_LOCATION["query"] = ma.RAISE
```
Another way of setting those values is to subclass the parser:

```py
MyFlaskParser(FlaskParser):
    DEFAULT_UNKNOWN_BY_LOCATION = {"query": ma.RAISE, "json": ma.RAISE,...}

MyBlueprint(Blueprint):
    ARGUMENTS_PARSER = MyFlaskParser()
```

I'm not convinced there's a real benefit in supporting an init parameter such as `flask_parser_kwargs`.

Note to OP: `DEFAULT_UNKNOWN_BY_LOCATION` must be set on the parser, not the schema.

Note to self: Update / fix documentation.

**Comment by camercu** [comment]
I tried mutating the parser instance created by flask-smorest's API, and that didn't work.

app.py:
```python
import typing

from flask import Flask
from flask.views import MethodView
from flask_marshmallow import Marshmallow
from flask_smorest import Api as _Api
from flask_smorest import Blueprint
from flask_sqlalchemy import SQLAlchemy
from marshmallow import EXCLUDE
from webargs.flaskparser import FlaskParser as _FlaskParser


class FlaskParser(_FlaskParser):
    DEFAULT_UNKNOWN_BY_LOCATION: typing.Dict[str, str] = {
        "json": EXCLUDE,
        "form": EXCLUDE,
        "json_or_form": EXCLUDE,
        "querystring": EXCLUDE,
        "query": EXCLUDE,
        "headers": EXCLUDE,
        "cookies": EXCLUDE,
        "files": EXCLUDE,
    }


class Api(_Api):
    ARGUMENTS_PARSER = FlaskParser()


app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:////tmp/test.db"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["API_TITLE"] = "My API"
app.config["API_VERSION"] = "v1"
app.config["OPENAPI_VERSION"] = "3.0.2"

db = SQLAlchemy(app)
ma = Marshmallow(app)
api = Api(app)

blp = Blueprint(
    "widgets",
    "widgets",
    url_prefix="/widgets",
    description="Operations on widgets",
)


class Widget(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(32), unique=True, nullable=False)
    color = db.Column(db.String(32), nullable=False, default="blue")

    def __repr__(self):
        return "<Widget %r>" % self.name


class WidgetSchema(ma.SQLAlchemySchema):
    class Meta:
        model = Widget
        unknown = EXCLUDE

    name = ma.auto_field(required=True)
    color = ma.auto_field(required=False)


@blp.route("/")
class Widgets(MethodView):
    @blp.response(WidgetSchema(many=True))
    def get(self):
        return Widget.query.all()

    @blp.arguments(WidgetSchema)
    @blp.response(WidgetSchema, code=201)
    def post(self, new_data):
        w = Widget(**new_data)
        db.session.add(w)
        return w


app.register_blueprint(blp)

if __name__ == "__main__":
    app.run(debug=True)
```

requirements.in:
```
flask
flask-marshmallow
flask-smorest
flask-sqlalchemy
marshmallow
marshmallow-sqlalchemy
pytest
```

test_app.py:
```python
import pytest
from app import Widget, app


@pytest.fixture
def db():
    from app import db

    with app.app_context():
        db.create_all()
        yield db
        db.session.close()
        db.drop_all()
        db.session.commit()


@pytest.fixture
def client(db):
    with app.app_context():
        with app.test_client() as client:
            yield client


def test_app(client, db):
    widget = Widget(name="Thingy")
    db.session.add(widget)
    db.session.commit()

    resp = client.get("/widgets/")
    got = resp.get_json()
    assert resp.status_code == 200, f"Bad status {resp.status_code}:\n{got}"
    assert len(got) == 1
    assert got[0]["name"] == "Thingy"

    new = {"name": "Whats-it", "color": "red", "detail": "this is ignored"}
    resp = client.post("/widgets/", json=new)
    got = resp.get_json()
    assert resp.status_code == 201, f"Bad status {resp.status_code}:\n{got}"
    assert got["name"] == new["name"]
```

Still errors out with HTTP 422 even though I set exclude as the rule for everything in the Api.ARGUMENTS_PARSER.DEFAULT_UNKNOWN_BY_LOCATION

**Comment by lafrech** [comment]
Oh boy. `ARGUMENTS_PARSER` is an attribute of `Blueprint`, not `Api`. My bad. Sorry for this.

Thanks for taking the time to write the repro case.

This is what you need to fix your example: 

```py
class Blueprint(_Blueprint):
    ARGUMENTS_PARSER = FlaskParser()
```

I definitely ought to document this correctly. Meanwhile, I fixed my comment above.

It is safe to mutate `DEFAULT_UNKNOWN_BY_LOCATION` in `webargs.flaskparser.FlaskParser` unless we want to instantiate several applications with different `unknown` settings, in which case subclassing is advised.

**Comment by lafrech** [comment]
I just updated the docs : https://flask-smorest.readthedocs.io/en/latest/arguments.html.

**Comment by Anti-Distinctlyminty** [comment]
Thanks for the additional docs.
One issue that I immediately hit is that practically all my endpoints have query parameters formed from multiple stacked `@Blupeprint.arguments`, e.g.

```python
    @bp.response(None)
    @bp.arguments(FieldKwargsSchema, location='query', as_kwargs=True)
    @bp.arguments(AnotherSchema, location='query', as_kwargs=True)
    def get(self, **kwargs):
        pass
```

**Comment by lafrech** [comment]
Well then default behaviour in webargs 7 should suit you, doesn't it?

**Comment by Anti-Distinctlyminty** [comment]
Apologies, I somehow skipped over a whole part! The behaviour I was looking for was to raise an exception if there are unknown query parameters that are not in the set of combined query parameters for the stacked `@Blueprint.arguments`.
In the example above `FieldKwargsSchema` contains `only` and `exclude`, and `AnotherSchema` contains `anotherId`. When performing a request that contains `only` and `anotherId`, then `AnotherSchema` raised an error 
```json
{
  "code": 422, 
  "status": "Unprocessable Entity", 
  "errors": {
    "query": {
      "only": [
        "Unknown field."
      ]
    }
  }
}```

**Comment by sirosen** [comment]
> The behaviour I was looking for was to raise an exception if there are unknown query parameters that are not in the set of combined query parameters

That's a different problem from the OP.
It can be done, but not in the way that you've phrased. If you want your sets of arguments merged, create a new schema with merges them -- then you can set `unknown=RAISE` and get the restrictive behavior. You could create a new schema explicitly, with inheritance, or with a schema-factory.


@lafrech, I think this issue is safe to close?

I'm happy to help add more doc -- even if it duplicates webargs docs somewhat -- but it looks like you've already taken care of the needful for this case.

**Comment by lafrech** [comment]
Yes, I think we can close this. I left it open intentionally at first to make it more visible because the change was recent and seemed to bring confusion.

Closing this brings down the list of open bugs to 25, a single page, so let's close.

Thanks for the doc fixes. Classes + plural is always awkward. I sometimes end up rewording as "``Class`` instances"...
