### ISSUE TITLE
 Object of type 'datetime' is not JSON serializable while rendering doc

### ISSUE THREAD

**Issue by loic001** [marshmallow-code/flask-smorest#34]
First of all, thank you for this lib :)

I got the following marshmallow schema :
```class MySchema(Schema):
    class Meta:
        strict = True
        ordered = True
        a_date = fields.DateTime(
            format='iso',
            missing=datetime.combine(date.today(), time()))
```
But it fails while rendering the doc (json schema) with the error :
```
 Object of type 'datetime' is not JSON serializable
```

It fails in In this [file](https://github.com/Nobatek/flask-rest-api/blob/master/flask_rest_api/spec/__init__.py)

```
json.dumps(self.spec.to_dict(), indent=2)
```

As a quick fix, I propose a simple datetime serializer:
```
def custom_date_serializer(obj):
    """Custom json serializer"""
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError ("Type %s not serializable" % type(obj))

json.dumps(self.spec.to_dict(), indent=2, default=custom_date_serializer)
```

**Comment by lafrech** [comment]
AFAIU, you want to default on current day, midnight.

I don't think `missing=datetime.combine(date.today(), time()))` is a good idea. Be aware that the function is executed at import time, so `date.today()` will be wrong after a few hours. You need to pass a callable. It can be a lambda.

If you're using apispec 0.x, the documentation of the default value will be the result of the callable at import time, which is a bit wrong as a default documentation. This is fixed in 1.x beta, where the callable is not called and the default value must be passed manually using `doc_default` (https://github.com/marshmallow-code/apispec/issues/196, https://github.com/marshmallow-code/apispec/pull/247).

Also, there may be issues with marshmallow 3.x beta and default values (https://github.com/marshmallow-code/apispec/issues/342).

Hope this helps.

**Comment by lafrech** [comment]
Also, if you're using marshmallow 2, you need to pass the default datetime in serialized form, so add `.isoformat()` to the result of the callable.

**Comment by loic001** [comment]
Very useful answer. Thanks for your help  !
