### ISSUE TITLE
How can I achieve this effect

### ISSUE THREAD

**Issue by sbigtree** [marshmallow-code/flask-smorest#357]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/48344438/168077319-6972b490-bd87-41c4-9fca-435f68c0d07f.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/48344438/168077354-30bb9ed2-48fa-4582-869b-3088dd189851.png">

**Comment by lafrech** [comment]
Hi.

I don't mind questions here since they may help improve the lib, but frankly this would be more suited on Q&A sites such as StackOverflow and even there you should really be more explicit and about what you want to achieve and what you've done so far. Right now, I (and other users here) can only try to guess what you want to do and I don't have time for that.

You may want to search for validate.OneOf in marshmallow/apispec. And perhaps Enum, although there is no direct support for it in the documentation generation in the marshmallow/apispec/flask-smorest stack.
