### ISSUE TITLE
Proper way to use schemas with alt_response?

### ISSUE THREAD

**Issue by GSGerritsen** [marshmallow-code/flask-smorest#413]
I have a route handler that looks like this:

```py
@bp.arguments(Args)
@bp.response(200, GoodResponse)
@bp.alt_response(400, schema=ErrorResponse)
def put(self, args):
    ...
    if errors:
        abort(400, errors=errors)
    else:
        return results
```

I've tried a few different variations in the error case to get things returning properly and validated according to the schema but can't get it working. Is it correct that the schema specified in `alt_response` will be used to validate and serialize the object returned in a `400` case here? I've experimented with putting invalid data into the `errors` object here, and it doesn't seem to make a difference.

My goal here is to return a 400 response with a JSON body that has the shape of `ErrorResponse`. Thanks in advance for any help!

**Comment by TheBigRoomXXL** [comment]
From what I understand alt_response only generate documentation. 

I think the easiest to validate the errors structure with your schema is to use ErrorResponse.dumps() directly.

For details on how alt_response is executed checkout [flask_smorest.response.py](https://github.com/marshmallow-code/flask-smorest/blob/5ac7296f98e9829059c4a7835c1ca2ffc1fdbdf8/flask_smorest/response.py )

**Comment by lafrech** [comment]
Indeed `alt_response` only documents. 

`abort(400,...)` should be enough to get what you expect since it will be caught by the default error handler.

In other words, your code look fine to me. The `else` is not need, though, since `abort` raises.

**Comment by mbernabo** [comment]
I agree that using abort to handle errors with the DEFAULT ERROR SCHEMA is straightforward and effective. However, I've noticed that this approach doesn't document the schema in the response properly. I could only get to show in the Swagger Doc the error pass to the abort method or additional info like the HTTP Code name.

How can I associate the default error schema with this alt_response to improve the documentation? Any advice on how to achieve this would be greatly appreciated. Thank you!

**Comment by lafrech** [comment]
If I understand the question correctly, pass the schema as [alt_response](https://flask-smorest.readthedocs.io/en/latest/api_reference.html#flask_smorest.Blueprint.alt_response) argument.

**Comment by mbernabo** [comment]
Yes, that was what I mean but how can I access that schema?

I thought something like: ` from flask_smorest.schemas import ErrorSchema`

Thanks for your fast reply and any additional help is kindly welcome.

**Comment by lafrech** [comment]
More like `Api.ERROR_SCHEMA` since it may be overridden.

People overriding default error handler should also update this schema for doc consistency.

**Comment by mbernabo** [comment]
Just to clarify (perhaps it's needed and I apologize if there was any confusion), what I'm trying to do is use the abort method and pass the arguments to the default error schema. That's working great but the only thing I'm not being able to do is document it properly. When I use the` alt_response` method I can pass an example but I am not being able to display (since the default schema is used) the default error schema. 

So the docs looks like this (See HTTP Code 409):

![Captura de pantalla 2024-05-24 a la(s) 1 37 36 p  m](https://github.com/marshmallow-code/flask-smorest/assets/70457237/60d99a9e-83ec-426c-b2d0-5495e65e8b39)

I just want to have the schema that will be using that error documented, so other developers can know what to expect in response.
