### ISSUE TITLE
Error response schema

### ISSUE THREAD

**Issue by qcho** [marshmallow-code/flask-smorest#44]
I've seen issue #19 and the recomendation instead of having more than one response is to use `@blp.doc`

The issue with this a approach is that it doesn't support any Schema information.

If we add schema as the object it doesn't work because it's not being replaced by it's json-schema's $ref
```py
@blp.doc(responses={
        '401': {'schema': GenericErrorSchema, 'description': 'Invalid credentials'}
    })
```

On the other hand when setting more than one `@blp.response` the openapispec is ok because it's using the autogenerated definition. The only issue is on the response serialization wrapper

Lot's of ideas come to my mind to fix this, but what do you think?
- Allow `@blp.response` with some extra param like `only_doc=True`
- Add `@blp.response_doc` to the `ResponseMixin` where `wrapper` just returns `result_raw`
- Allow using `@blp.doc(responses=...)` with GenericErrorSchema
- Make my `GenericErrorSchema` json encode into a `$ref` dict by calling something like [OpenAPIConverter.get_ref_dict](https://apispec.readthedocs.io/en/stable/api_ext.html#apispec.ext.marshmallow.openapi.OpenAPIConverter.get_ref_dict)

**Comment by qcho** [comment]
<img width="534" alt="app____Code_nerd_app__-_____venv_lib_python3_7_site-packages_flask_rest_api_spec___init___py" src="https://user-images.githubusercontent.com/185588/54076400-0ea31680-428a-11e9-83ad-324ac68fbcb1.png">

**Comment by qcho** [comment]
Maybe I want errors from automatic validation to be documented
<img width="596" alt="app" src="https://user-images.githubusercontent.com/185588/54076561-dc92b400-428b-11e9-9d1d-b57a1a94edd9.png">

**Comment by qcho** [comment]
Ended up adding this method:

```py
from werkzeug.exceptions import HTTPException
from marshmallow import Schema, fields

class HttpErrorSchema(Schema):
    status = fields.String(required=True, description='A description of the error')

def response_error(error: HTTPException):
    """
    A decorator to protect a Flask endpoint.

    If you decorate an endpoint with this it documents http-exception
    """
    def decorator(fn):
        doc = {
            'responses': {
                str(error.code): {'schema': HttpErrorSchema(), 'description': error.description}
            }
        }
        fn._apidoc = deepupdate(getattr(fn, '_apidoc', {}), doc)

        @wraps(fn)
        def wrapper(*args, **kwargs):
            return fn(*args, **kwargs)
        return wrapper
    return decorator
```

Now i can add `@response_error(Conflict('Email exists'))` decorator and it will document the later
`raise Conflict('Email exists')`

**Comment by lafrech** [comment]
Nice.

This question raises fair points.

The idea behind flask-rest-api is that the doc is generated by the code, and this is the main use case. With our own usage and user feedback, we came to realize that sometimes, documentation must be added manually as it can't be introspected from the code.

This was already discussed in #23, where the user wants to document extra parameters (actually, add extra documentation to auto-documented parameters). This is a corner case.

Also, I like to consider `@blp.doc` as a last resort for features not available yet. Although admittedly it is needed in many cases.

I'd rather avoid adding a clumsy `only_doc` parameter. And I don't like the idea of `response_doc` and `arguments_doc` decorators. Maybe the proper way to go would be to use `response` and `arguments` only to document, and use `use_args` / `marshal_with` (the names we used in the past, borrowed from webags and flask-apispec) when actual work is needed, calling the documentation decorators internally. Obviously, that's a totally breaking change, but it's a simple find'n replace. I'd rather not jump to that too quickly, let's take the time to think it through. Feedback welcome.

Meanwhile, this week-end, I've been working on improving error documentation. I'm not done yet. I plan on adding a default error on all resources exposing the error structure, as well as a 422 error on resources using the `arguments` decorator. I should also auto-document ETag related errors.

The few changes I have in mind might also help with manual error response registration.

Since another assumption made by the framework is that a resource only has one success status and the rest is errors, the `response` decorator works fine and only errors need to be documented separately. So maybe a decorator only documenting errors would be enough. Your implementation looks neat, thanks for sharing.

**Comment by lafrech** [comment]
0.19 adds auto-documentation of errors generated by stock decorators (arguments, response, etag).

The internal mechanisms have changed. The code above won't work anymore. Such custom decorators should copy what is done in stock decorators. Also see explanation in CHANGELOG and in blueprint.py docstring.

I still like the idea of adding a decorator to declare errors, even if it is less critical now that most errors are automatically documented.
