### ISSUE TITLE
Transactional tests

### ISSUE THREAD

**Issue by kettenbach-it** [marshmallow-code/flask-smorest#457]
Is it possible to make end-to-end tests done via the REST API transactional, i.e. that I can do a `rollback()` after the tests are finished and the database is therefore not touched?

**Comment by davidism** [comment]
Note that they also tried to ask this on the Flask issue tracker, and I told them that it's not within Flask's or Flask-Smorest's control to manage database transactions during tests. I recommend closing this.

**Comment by lafrech** [comment]
I don't know what other people do. I guess some use a dedicated DB for tests. Other use a DB mock. In our projects, we use pytest-postgresql so that our tests require postgresql binary but databases are created on-the-fly.

In any case, this is indeed out of scope here, as you were told [here](https://github.com/pallets/flask/issues/4962) already.

**Comment by kettenbach-it** [comment]
@lafrech Thank you for helping even though the Python Police wanted to stop it!

**Comment by lafrech** [comment]
There is no Python police, here. Only benevolent OSS maintainers doing their best.

(Edit: To be explicit, "here" referred to this thread and includes pallets org maintainers.)

**Comment by kettenbach-it** [comment]
;-)
