### ISSUE TITLE
Changing the Pagination response Format

### ISSUE THREAD

**Issue by TGoddessana** [marshmallow-code/flask-smorest#494]
**hi, first of all, thank you for creating such a great framework!**

is there any way to change the pagination response format in flask-smorest to suit my needs?

for example DRF provides the following response format by default:

```json

{
  "results":[] # some items..
  "next" : # next page url..
  "prev" : # previous page url..
}

```

is there a way to do that in flask-smorest?

currently, im defining and using a separate schema, like below:

```python

class PaginateArgsSchema(Schema):
    page = fields.Integer(
        load_default=1,
        validate=Range(min=1),
    )
    per_page = fields.Integer(
        load_default=10,
        validate=Range(min=1),
    )



class PaginationResultSchemaMixin:
    count = fields.Integer()
    next_num = fields.URL()
    previous_num = fields.URL()


class UserListSchema(PaginationResultSchemaMixin, Schema):

    results = fields.List(
        fields.Nested(UserSchema())}
    )


```

and i get this response:

```json

{
  "count": 1,
  "next_num": null,
  "previous_num": null,
  "results": [
    {
      "email": "twicegoddessana1229@gmail.com",
      "id": 1,
      "username": "goddessana",
      "uuid": "319f8538-4e32-467e-a38c-5ad1c30e9b8e"
    }
  ]
}

```

but - I keep getting the feeling that i'm not using Flask-Smorest's capabilites correctly.

**Comment by lafrech** [comment]
Hi. Thanks for the kind words.

flask-smorest does not do that but since people have been asking for it, I added an exemple in the tests:

https://github.com/marshmallow-code/flask-smorest/blob/9b534fd00f9618f825516c9dbdf37b2e6f69b12e/tests/test_examples.py#L390

The good thing with it being in the tests is that it prevents the use case from being broken (or at least I'll adapt the example).

I hope this helps.

**Comment by TGoddessana** [comment]
thanks, i didn't know there was such a great examples!
