### ISSUE TITLE
Schema Validation on Patch

### ISSUE THREAD

**Issue by DNCoelho** [marshmallow-code/flask-smorest#50]
So I was trying t implement a simple Patch use case but its proving to be a difficult affair. As Patch allows for partial submission of schema fields I tried the obvious solution and added the partial=True argument to my schema declaration. 

`@blp.arguments(UserInputSchema(partial=True))`

This however leads to a problem related to the marshmallow model schema class, since it immediately tries to  create a model instance from the passed object.

Am I missing something or does patch just not play well with the intended behavior of marshmallow's ModelSchema?

Thanks for the help in advance.

**Comment by lafrech** [comment]
Patching is indeed complicated stuff.

What you're trying to do is not a real patch but a put-like patch. It does not allow deleting a field, for instance. 

A real patch would require something like json-patch. Search for json-patch on the Internet to get a better idea of what I'm talking about. I don't do that and I have no recommendation.

This said, I think a lot of people live happily with put-like patches, which are much easier to achieve. I don't do that either, I only use PUT.

> This however leads to a problem related to the marshmallow model schema class, since it immediately tries to create a model instance from the passed object.

I think this is due to your schema. You must have some `post_load` decorator instantiating a model class, right?

I generally don't to that. The schema deserializes the data and passes it to the view function as a `dict`. Then the view function uses it to update the data.

I think passing `partial=True` should do what you want.

```py
@blp.route(.../<item_id>)
class UserInputById(MethodView):
    @blp.arguments(UserInputSchema(partial=True))
    @blp.response(UserInputSchema)
    def patch(self, new_data, user_input_id):
        # 1/ Get item object (using ORM/ODM)
        user_input = UserInput.get(user_input_id)
        # At this stage, new_data is a dict, user_input is an object
        # 2/ Update item with new_data
        # I don't have a generic method for that.
        # I suppose it depends on the application, the ORM/ODM, etc.
        # Doing it field by field can be verbose.
        [...]
        # 3/ Save item
        user_input.save()
        # 3/ Return item
        return user_input
```

Hope this helps.

**Comment by DNCoelho** [comment]
Thank you for the fast response, it does help. You confirmed what I thought.  While I don't directly use any post_load decorator the class responsible for interpreting a model and building a schema, marshmallow's ModelSchema does have one:


    @ma.post_load
    def make_instance(self, data):
        """Deserialize data to an instance of the model. Update an existing row
        if specified in `self.instance` or loaded by primary key(s) in the data;
        else create a new row.

        :param data: Data to deserialize.
        """
        instance = self.instance or self.get_instance(data)
        if instance is not None:
            for key, value in iteritems(data):
                setattr(instance, key, value)
            return instance
        kwargs, association_attrs = self._split_model_kwargs_association(data)
        instance = self.opts.model(**kwargs)
        for attr, value in iteritems(association_attrs):
            setattr(instance, attr, value)
        return instance

I suppose this means I should use a properly defines schema for any model and avoid using the ModelSchema class since it will always lead too this type of scenario.

**Comment by lafrech** [comment]
Looks like you're using marshmallow-sqlalchemy. I have no experience with it so I can't help.

I've been using sqlalchemy once and I defined the schemas manually. I think I didn't use marshmallow-sqlalchemy because it didn't allow me to express all the validation constraints I wanted to add to the fields, so there was so much to tweak in auto-generated schemas I was better off crafting them from scratch. It is possible that this was due to my own ignorance and I could have achieved better using marshmallow-sqlalchemy but I didn't have the time to investigate.

**Comment by DNCoelho** [comment]
I can understand that. Thank you for the help!

**Comment by BorjaEst** [comment]
From the functionality point of view `partial=True` works perfectly. Note  json-patch is not now the only way to perform PATCH but also the method described here. See [rfc7396](https://datatracker.ietf.org/doc/html/rfc7396).

The bad side of `partial=True` is that it creates a new schema followed by '1'.
Here would produce `UserInputSchema` and `UserInputSchema1` schemas on the OpenAPI spec.

For someone looking to something similar:
```py

class UserInputSchemaEdit(UserInputSchema):
    class Meta:
        fields = (...,)

    def __init__(self, *args, partial=None, **kwargs):
        super().__init__(*args, partial=True, **kwargs)

``` 

Then the available schemas at the OpenAPI spec would be `UserInputSchemaEdit` and `UserInputSchema`.

**Comment by lafrech** [comment]
You shouldn't have to override init. There won't be any 1 appended if you only ever call the Edit schema with partial=True.
