### ISSUE TITLE
The error handler intercepts trailing slash redirect

### ISSUE THREAD

**Issue by steinitzu** [marshmallow-code/flask-smorest#51]
I had an issue with URLs with trailing slash where flask would normally redirect. 
e.g. `@blp.route('/things/')` , a request for `/things` should redirect to `/things/` by default.  

Example:

```python
from flask import Flask
from flask_rest_api import Api, Blueprint

app = Flask(__name__)
app.config['OPENAPI_VERSION'] = '3.0.2'

api = Api(app)


blp = Blueprint('blp', __name__)


@blp.route('/things/')
def get_things():
    return 'things'


api.register_blueprint(blp)
```

When calling the endpoint without the trailing slash you get a serialized 308 response with no Location header instead of a proper redirect response:

```
curl -i http://localhost:5001/things
HTTP/1.0 308 PERMANENT REDIRECT
Content-Type: application/json
Content-Length: 42
Server: Werkzeug/0.15.1 Python/3.6.7
Date: Tue, 26 Mar 2019 20:57:42 GMT

{"status":"308 Permanent Redirect: None"}
```
Is this expected?

I looked at the errorhandler code and saw it captures any type of `HTTPException`, but the redirect triggers a `werkzeug.routing.RequestRedirect` which is a subclass of `HTTPException` and `RoutingException`

I worked around this in my app by overriding `handle_http_exception` like this

```python
from flask_rest_api import Api as BaseApi
from werkzeug.routing import RoutingException

class Api(BaseApi):
    def handle_http_exception(self, error):
        # Don't serialize redirects
        if isinstance(error, RoutingException):
            return error
        return super().handle_http_exception(error)
```

But the framework probably should only register an error handler for codes above 400.

Cheers

**Comment by lafrech** [comment]
Hi. Sorry for the delay.

I'm not sure about this. I really need to get my head around it. I don't think it is only about 3XX vs. 4XX.

The default error handling mechanism here is meant to allow the user to `abort` with a properly json-formatted meaningful message.

Apparently, Flask raises on 308 then I guess it catches its own exception to add the `Location` header, which we prevent in flask-rest-api. We shall investigate, because there may be other similar cases.

Hopefully, we can find an elegant solution to this.

Ultimately, I don't consider this critical. Redirections are nice for humans (browsing the Internet, manually playing with an API) but APIs are meant for machines to consume, and if the URL is /things/, the machine should ask for /things/, not /things.

**Comment by steinitzu** [comment]
Hi, thanks for getting back

After some more thought this particular issue for me is really a side of effect of how the `Api` catches errors for the whole app.

I don't really care about the redirects in my API, but I also have some frontend routes that don't have anything to do with flask-rest-api in the same app and redirects broke in the frontend when I introduced flask-rest-api for the API parts.

So I want to first explore ways to only handle errors originating from routes registered on the `Api` instance. If you're open to it I can do  PR if I find a nice way to do it.
I think flask-restplus does something similar (just from glancing at their code, haven't used it), but it could be even simpler here cause we're always dealing with blueprints, so might work to just use `blueprint.register_errorhandler` instead of the app level errorhandler.

**Comment by lafrech** [comment]
> So I want to first explore ways to only handle errors originating from routes registered on the Api instance. If you're open to it I can do PR if I find a nice way to do it.

Good. I'd be open to that. Especially since currently the error handlers also catch errors in the documentation (ReDoc / Swagger UI) blueprint, which is not really wanted but is the same side-effect that affects your application.

> might work to just use blueprint.register_errorhandler instead of the app level errorhandler.

Sounds appealing, but it doesn't work for 404 and 500.

http://flask.pocoo.org/docs/1.0/api/#flask.Blueprint.errorhandler

> Registers an error handler that becomes active for this blueprint only. Please be aware that routing does not happen local to a blueprint so an error handler for 404 usually is not handled by a blueprint unless it is caused inside a view function. Another special case is the 500 internal server error which is always looked up from the application.

> I think flask-restplus does something similar (just from glancing at their code, haven't used it)

Could be interesting to see how they do that.

---------------------------------------------------------------------------------

This error handler is something we added a while back. It is mostly useful to make error payloads consistent across errors and to provide a structure that can be easily parsed by a program. In practice, the only use case I can think of that really takes advantage of the JSON structure of the error payload is the validation error that results in a 422, where the marshmallow error is returned. In the general case, the mechanism might not be that useful as there is no payload structure to parse from the client (Or is there? Anyone has a use case in mind?).

Maybe we should only register a handler on 422 error (in practice, on the error code associated to validation error in webargs, which defaults to 422).

This is kinda related to #35.

**Comment by steinitzu** [comment]
> Sounds appealing, but it doesn't work for 404 and 500.

Ah, good catch. I didn't know that, but makes sense. Tricky to handle 404s like this in general if they don't happen within a route function.
Maybe we could determine if the 404 belongs to the api if the url is within an api blueprint's `url_prefix`, but that sounds a bit hacky.

> Maybe we should only register a handler on 422 error (in practice, on the error code associated to validation error in webargs, which defaults to 422).

I personally like having it, I usually create a similar errorhandler myself if only for consistency so clients can expect all responses to be JSON and errors have x,y,z attributes.

**Comment by lafrech** [comment]
This issue is two-fold.

1/ The generic error handler is used application-wise, including optional online documentation (ReDoc or Swagger-UI) and any other route defined in the app.

2/ The automatic redirection that comes with 308 errors is screwed by the error handler.

--------------------------------------------------------------------------------------------------------

1/ I don't see an easy and generic way around this. For 404 and 500, it seems impossible, and for the other errors, it wouldn't be easy. In practice, I don't think it is that bad. Having a single app with both API and other routes sounds like a corner case. Legit case, but this issue just slightly degrades user experience, it doesn't make it impossible to achieve, so I don't mind keeping things as is. Likewise, the impact on documentation blueprint is neglectable. Besides, I find the embedded documentation feature a killer feature when developing, and I use it on all my projects, but ultimately, a huge API in production would probably deploy the documentation statically on a separate app.

2/ I've been digging into werkzeug to figure out what is going on. It seems 308 is the only error affected by this. 

`RequestRedirect` implements a get_response method doing the redirection:

```py
def get_response(self, environ=None):
    return redirect(self.new_url, self.code)
```

Looks like the whole `get_response` mechanism is only used by this exception.

We could add code in flask-smorest to manage `RequestRedirect` specifically but I'd rather avoid useless complexity and this is easily achieved in user code as you shown.

--------------------------------------------------------------------------------------------------------

Overall, I'm leaning towards leaving thing as is.

Please comment if you feel otherwise.
