### ISSUE TITLE
Create `register_schema` method in `flask_rest_api.Api`

### ISSUE THREAD

**Issue by jtmiclat** [marshmallow-code/flask-smorest#76]
Hi!

I want to start off with saying I am really thankful for work on this library.

The way I prefer structuring my flask app is via application factory but defining a schema, as suggested in the documentation, requires an instance of `flask_rest_api.Api`. I suggest creating a method in called `register_schema` an alternative to the `schema` decorator. Usage will be similar to `register_blueprints`. 

```
from flask import Flask
from flask_rest_api import Api

from . import schemas

def create_app(config):
     app = Flask(__name__)
     api = Api(app)
     register_api_schemas(api)
     register_api_blueprint(api)
     return app

def register_schemas(api):
     api.register_schema("Foo", schemas.FooSchema)
     api.register_schema("Bar", schemas.BarSchema) 
```

My current work around  is something like
````
def register_schemas(api):
     api.schema("Foo")(schemas.FooSchema)
     api.schema("Bar")(schemas.BarSchema) 
````

**Comment by lafrech** [comment]
I don't really see what difference this would make. Is it only cosmetic or am I missing the point? As you noticed, the decorator method can be called without the `@` decorator syntax.

Anyway, since schemas are registered automatically thanks to apispec, I don't think this is needed at all. In fact, I'm thinking of removing the `schema` decorator.

Please see 

- https://github.com/Nobatek/flask-rest-api/issues/38#issuecomment-495527421
- https://github.com/Nobatek/flask-rest-api/issues/43#issuecomment-495357970
- https://github.com/Nobatek/flask-rest-api/pull/75

**Comment by jtmiclat** [comment]
Oh Cool! If schema are automatically registered then I suppose this isn't needed anymore. Thanks!
